name:  ParallelsDesktopCrack

on:
  workflow_dispatch:

  schedule:
    - cron: '0 0/12 * * *'

jobs:
  ParallelsDesktopCrack:
    name: ParallelsDesktop
    runs-on: ubuntu-latest
    steps:
      - name: ParallelsDesktopCrack
        run: |
            git clone https://git.icrack.day/somebasj/ParallelsDesktopCrack.git 
            cd ParallelsDesktopCrack 
            git checkout remotes/origin/main
            git push https://${{secrets.TOKEN}}@github.com/dreamncn/ParallelsDesktopCrack.git HEAD:main --force
      - name: ParallelsToolboxCrack
        run: |
            git clone https://git.icrack.day/somebasj/ParallelsToolboxCrack.git 
            cd ParallelsToolboxCrack 
            git checkout remotes/origin/main
            git push https://${{secrets.TOKEN}}@github.com/dreamncn/ParallelsToolboxCrack.git HEAD:main --force       
        
        
